from django.urls import path
from webapp import views


urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("admin/devices", views.devices_page, name="devices_page"),
    path("admin/schedule", views.schedule_page, name="schedule_page"),
    path("admin/manage/<str:entity>", views.manage_entity_page, name="manage_entity_page"),
    path("admin/defaulters", views.defaulters_page, name="defaulters_page"),
    path("admin/monthly", views.monthly_page, name="monthly_page"),
    path("", views.welcome, name="welcome"),
    path("student", views.student, name="student"),
    path("student-profile", views.student_profile_page, name="student_profile_page"),
    path("faculty-workbench", views.faculty_workbench_page, name="faculty_workbench_page"),
    path("smart-food", views.smart_food_page, name="smart_food_page"),
    path("smart-food/menu", views.smart_food_menu_page, name="smart_food_menu_page"),
    path("smart-food/checkout", views.smart_food_checkout_page, name="smart_food_checkout_page"),
    path("smart-food/orders", views.smart_food_orders_page, name="smart_food_orders_page"),
    path("smart-food/kitchen", views.smart_food_kitchen_page, name="smart_food_kitchen_page"),
    path("campus-resource", views.campus_resource_page, name="campus_resource_page"),
    path("makeup-class", views.makeup_class_page, name="makeup_class_page"),
    path("payments", views.payments_page, name="payments_page"),
    path("ops-center", views.ops_center_page, name="ops_center_page"),
    path("payment-success", views.payment_success_page, name="payment_success_page"),
    path("admin", views.admin_page, name="admin_page"),
    path("admin/", views.admin_page),
    path("api/enroll", views.api_enroll, name="api_enroll"),
    path("api/train", views.api_train, name="api_train"),
    path("api/recognize", views.api_recognize, name="api_recognize"),
    path("api/status", views.api_status, name="api_status"),
    path("api/recent", views.api_recent, name="api_recent"),
    path("api/export", views.api_export, name="api_export"),
    path("api/export-pdf", views.api_export_pdf, name="api_export_pdf"),
    path("api/reset-today", views.api_reset_today, name="api_reset_today"),
    path("api/admin/login", views.api_admin_login, name="api_admin_login"),
    path("api/admin/logout", views.api_admin_logout, name="api_admin_logout"),
    path("api/dashboard", views.api_dashboard, name="api_dashboard"),
    path("api/devices", views.api_devices, name="api_devices"),
    path("api/defaulters", views.api_defaulters, name="api_defaulters"),
    path("api/monthly-report", views.api_monthly_report, name="api_monthly_report"),
    path("api/makeup/sessions", views.api_makeup_sessions, name="api_makeup_sessions"),
    path("api/makeup/create", views.api_makeup_create, name="api_makeup_create"),
    path("api/food/place-order", views.api_place_food_order, name="api_place_food_order"),
    path("api/food/update-status", views.api_food_update_status, name="api_food_update_status"),
    path("api/payment/qr-received", views.api_qr_payment_received, name="api_qr_payment_received"),
    path("api/payment/phonepe/webhook", views.api_phonepe_webhook, name="api_phonepe_webhook"),
    path("api/payment/status", views.api_payment_status, name="api_payment_status"),
    path("api/payment/submit-upi-proof", views.api_submit_upi_proof, name="api_submit_upi_proof"),
    path("api/payment/admin-review", views.api_admin_payment_review, name="api_admin_payment_review"),
    path("api/payment/dispute", views.api_payment_dispute, name="api_payment_dispute"),
    path("api/payment/refund", views.api_payment_refund, name="api_payment_refund"),
    path("api/payment/upload-proof", views.api_payment_upload_proof, name="api_payment_upload_proof"),
    path("api/schedule/suggestions", views.api_schedule_suggestions, name="api_schedule_suggestions"),
    path("api/analytics/summary", views.api_analytics_summary, name="api_analytics_summary"),
    path("api/lecturer/login", views.api_lecturer_login, name="api_lecturer_login"),
    path("api/lecturer/logout", views.api_lecturer_logout, name="api_lecturer_logout"),
]
