# Generated by Django 5.1.6 on 2026-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_breaktimeslot_campusblock_fooditem_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='order_mode',
            field=models.CharField(choices=[('dining', 'Dining'), ('delivery', 'Delivery')], default='dining', max_length=20),
        ),
    ]
