# Generated by Django 5.1.6 on 2026-02-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_foodorder_delivery_location_foodorder_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Main Course', 'Main Course'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages'), ('Desserts', 'Desserts')], default='Main Course', max_length=40),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
