# Generated by Django 5.1.6 on 2026-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_fooditem_category_fooditem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('upi', 'UPI'), ('qr', 'QR'), ('card', 'Card'), ('cash', 'Cash'), ('wallet', 'Wallet')], default='upi', max_length=20),
        ),
    ]
